### ISSUE TITLE
achoz engine fails 

### ISSUE THREAD

**Issue by jcm4atx** [kcubeterm/achoz#28]
When I run `achoz engine` I get this...

```
I20220101 16:41:18.443842 2033983 typesense_server_utils.cpp:306] Starting Typesense 0.22.1
I20220101 16:41:18.443964 2033983 typesense_server_utils.cpp:309] Typesense is using jemalloc.
I20220101 16:41:18.444278 2033983 typesense_server_utils.cpp:358] Thread pool size: 32
I20220101 16:41:18.448292 2033983 store.h:61] Initializing DB by opening state dir: /home/jcm/.achoz/searchdb/db
I20220101 16:41:18.696844 2033983 store.h:61] Initializing DB by opening state dir: /home/jcm/.achoz/searchdb/meta
I20220101 16:41:18.911377 2033983 typesense_server_utils.cpp:437] Starting API service...
I20220101 16:41:18.911537 2034104 typesense_server_utils.cpp:209] Since no --nodes argument is provided, starting a single node Typesense cluster.
I20220101 16:41:18.911878 2033983 http_server.cpp:172] Typesense has started listening on port 8909
I20220101 16:41:18.911928 2034105 batched_indexer.cpp:120] Starting batch indexer with 32 threads.
I20220101 16:41:18.913426 2034105 batched_indexer.cpp:126] BatchedIndexer skip_index: -9999
E20220101 16:41:18.917851 2034104 server.cpp:955] Fail to listen 10.0.0.32:8107
E20220101 16:41:18.917901 2034104 typesense_server_utils.cpp:245] Failed to start peering service
report error
```

I'm not sure why it's listening on 10.0.0.32:8107. I believe it should be 192.168.0.32:8107. That could be the issue, but I'm not clear if Typesense or Achoz is issuing this.

**Comment by jcm4atx** [comment]
I solved my own problem. I'm keeping this here in case someone else has the issue. It was binding to the wrong IP address. The solution is to edit `/etc/typesense/typesense-server.ini` and add the correct one. In my case...

`peering-address = 192.168.0.32`

Your address might differ.

**Comment by kcubeterm** [comment]
> I'm not sure why it's listening on 10.0.0.32:8107. I believe it should be 192.168.0.32:8107

Thats typesense node itself. Which runs on multiple node so that even if few node fails it still able to serve you.

**Comment by kcubeterm** [comment]
BTW, you can disable typesense server which is started by systemctl if you dont use it. since achoz start own instance of typesense server.
