### ISSUE TITLE
unsanitary layout bug

### ISSUE THREAD

**Issue by cauerego** [kcubeterm/achoz#30]
https://achoz.ahoxus.org/search?q=hello&page=4

![Screenshot_20220106-225542](https://user-images.githubusercontent.com/560418/148464060-40e370fc-e8c0-4481-92d0-eb379e6dc047.png)

page 3 have another similar bug, but i won't bother to post it. 😘

**Comment by kcubeterm** [comment]
of course, sanitization is essential steps, as it will save disk as well as precious RAM.

**Comment by kcubeterm** [comment]
I noticed, few PDF files output huge non printable character. that also need to sanitise.

**Comment by cauerego** [comment]
not sure if this specific case can save disk or ram, plus i don't think it would offer much practical improvement.

it appears to be only a layout bug with the only practical improvement to prevent unexpected behaviour, such as missing layout. (in the screenshot, it should say "text" there, but luckily the next button was intact).

when we fix this, i would suggest to add a tag to the fixed search result: "sanitised". with a link to bob tables xkcd. 🤣

**Comment by kcubeterm** [comment]
> not sure if this specific case can save disk or ram, plus i don't think it would offer much practical improvement.

It will, I'm talking about sanitisation with crawler side as well. I noticed some pdf files output KBs of non-printable character which is useless.

**Comment by cauerego** [comment]
fair enough. from my search experience, though, this bug is rare enough that a few kB should still turn into insignificant improvement, when fixed. most likely for most datasets, at least.

not sure how we could classify issues priorities here... i would say this should be very low and avoided for now unless it's super easy to fix.

a simple sanitiser might be simple enough. a complete one might not.
