### ISSUE TITLE
[bug] fs.existsSync not working well, retuns "false" even if directory exists. 

### ISSUE THREAD

**Issue by kcubeterm** [kcubeterm/achoz#38]
https://github.com/kcubeterm/achoz/blob/30d404554a4feddc510a613ff4bc1b72e0373132/crawler/crawler.js#L21 

here it is. 

![Screenshot from 2022-01-29 21-12-10](https://user-images.githubusercontent.com/50498359/151668010-2c8d3f4b-0568-4517-bf90-0e715d20f2ee.png)

as image shown. different behaviour of fs.existSync() . the crawler.js returning false while node shell returns true.

**Comment by cauerego** [comment]
looks like it's a better js design practice to avoid using existsSync anyway.

rather use error handling.

https://stackoverflow.com/questions/28532820/fs-exists-fs-existssync-why-are-they-deprecated

**Comment by kcubeterm** [comment]
Fs.statSync is also returns error says no such file or directory, more weird things is it happens on few directory and files not all. 

These type of function should be reliable at least.

**Comment by kcubeterm** [comment]
anyway look like it is working fine with absolute path

**Comment by cauerego** [comment]
you know jsisweird.com right?

if it works with absolute path, that explains a lot already...

but i would rather keep this issue open (if you will) as to remember the idea of replacing it for error handling...

at very least i will try to tag this issue differently.

**Comment by kcubeterm** [comment]
> you know jsisweird.com right?

yes.

**Comment by kcubeterm** [comment]
Rewritten into python.
